import Head from "next/head";
import Container from "react-bootstrap/Container";
import Navigation from "../../components/navigation";

export default function (props) {
  const { title, children } = props;
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigation />
        <Container>{children}</Container>
      </main>
    </div>
  );
}
